[package]
name = "dmntk-gendoc"
version = "0.0.7"
authors = ["Dariusz Depta <dariusz.depta@engos.software>"]
description = "DMNTK | DMN model and parser"
documentation = "https://docs.rs/dmntk-model"
repository = "https://github.com/dmntk/model.git"
license = "MIT"
edition = "2018"

[dependencies]
dmntk-examples = "0.0.7"
dmntk-model = "0.0.7"